services:
  - type: web
    plan: free
    name: teldrive
    env: docker
    repo: https://github.com/Kkbrothers8795/teldrive
    branch: main
    autoDeploy: false
    healthCheckPath: /
    envVars:
      - key: PORT
        value:
