services:
  - type: web
    plan: free
    name: teldrive
    runtime: docker
    repo: https://github.com/Kkbrothers8795/teldrive.git
    branch: main
    autoDeploy: false
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 8080
