services:
  imagor:
    image: ghcr.io/divyam234/imagor
    container_name: imagor
    restart: always
    volumes:
      - ./imagestore:/home/user/imagor_storage
    ports:
      - 8000:8000
    environment:
      IMAGOR_UNSAFE: 1
      FILE_RESULT_STORAGE_BASE_DIR: /home/user/imagor_storage
      FILE_RESULT_STORAGE_MKDIR_PERMISSION: 0755 
      FILE_RESULT_STORAGE_WRITE_PERMISSION: 0666